# Generated by Django 5.2.5 on 2025-08-29 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='medicaments',
        ),
        migrations.AddField(
            model_name='consultation',
            name='rendez_vous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sante_app.rendezvous'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medecin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
        migrations.AlterModelTable(
            name='constante',
            table='Constante',
        ),
        migrations.AlterModelTable(
            name='consultation',
            table='Consultation',
        ),
        migrations.AlterModelTable(
            name='medecin',
            table='Medecin',
        ),
        migrations.AlterModelTable(
            name='medicament',
            table='Medicament',
        ),
        migrations.AlterModelTable(
            name='mesure',
            table='Mesure',
        ),
        migrations.AlterModelTable(
            name='pathologie',
            table='Pathologie',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='Patient',
        ),
        migrations.AlterModelTable(
            name='rendezvous',
            table='RendezVous',
        ),
        migrations.AlterModelTable(
            name='service',
            table='Service',
        ),
        migrations.AlterModelTable(
            name='structuredesante',
            table='StructureDeSante',
        ),
        migrations.AlterModelTable(
            name='traitement',
            table='Traitement',
        ),
        migrations.AlterModelTable(
            name='user',
            table='utilisateur',
        ),
    ]
