# Generated by Django 5.2.5 on 2025-09-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0004_clinique_dentiste_hopital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ouvert_24h', models.BooleanField(default=False)),
            ],
        ),
    ]
