# Generated by Django 5.2.5 on 2025-09-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0005_pharmacie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinique',
            name='specialite',
        ),
    ]
