# Generated by Django 5.2.5 on 2025-09-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0007_contactfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
