# Generated by Django 5.2.5 on 2025-10-07 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0008_user_adresse_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé'), ('RESCHEDULED', 'Reprogrammé'), ('PENDING', 'En attente')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_medecin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
