# Generated by Django 5.2.5 on 2025-10-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0009_rendezvous_statut_alter_rendezvous_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_user', models.TextField(verbose_name='Message utilisateur')),
                ('message_bot', models.TextField(verbose_name='Réponse chatbot')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sentiment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='sante_app.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
