# Generated by Django 5.2.5 on 2025-10-10 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0010_chatbotconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RappelMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=100, verbose_name='Nom du médicament')),
                ('dosage', models.CharField(max_length=50, verbose_name='Dosage')),
                ('frequence', models.CharField(max_length=50, verbose_name='Fréquence')),
                ('heure_rappel', models.TimeField(verbose_name='Heure du rappel')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True, verbose_name='Rappel actif')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes supplémentaires')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels_medicaments', to='sante_app.patient')),
            ],
            options={
                'verbose_name': 'Rappel médicament',
                'verbose_name_plural': 'Rappels médicaments',
                'ordering': ['heure_rappel'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePriseMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prise', models.DateTimeField(auto_now_add=True, verbose_name='Date de prise')),
                ('prise_effectuee', models.BooleanField(default=False, verbose_name='Prise effectuée')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('rappel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_prises', to='sante_app.rappelmedicament')),
            ],
            options={
                'verbose_name': 'Historique prise médicament',
                'verbose_name_plural': 'Historiques prises médicaments',
                'ordering': ['-date_prise'],
            },
        ),
    ]
