# Generated by Django 5.2.4 on 2025-10-10 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0012_clinique_latitude_clinique_longitude_and_more'),
    ]

    operations = [
        # Delete the old Article model
        migrations.DeleteModel(
            name='Article',
        ),
        # Create the new Article model
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('resume', models.TextField(max_length=500, verbose_name='Résumé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('categorie', models.CharField(choices=[('prevention', 'Prévention'), ('nutrition', 'Nutrition'), ('maladies', 'Maladies'), ('bien_etre', 'Bien-être'), ('grossesse', 'Grossesse'), ('pediatrie', 'Pédiatrie'), ('geriatrie', 'Gériatrie'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('desactive', 'Désactivé')], default='brouillon', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_moderation', models.TextField(blank=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('vues', models.IntegerField(default=0)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article de Santé',
                'verbose_name_plural': 'Articles de Santé',
                'ordering': ['-date_publication'],
                'db_table': 'Article',
            },
        ),
    ]