# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0013_update_article_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_urgence', models.CharField(max_length=100, verbose_name="Type d'urgence")),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('symptomes', models.TextField(verbose_name='Symptômes')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('critique', 'Critique')], default='moyenne', max_length=20)),
                ('priorite_automatique', models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('critique', 'Critique')], max_length=20)),
                ('score_urgence', models.IntegerField(default=0, help_text='Score calculé automatiquement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('prise_en_charge', 'Prise en charge'), ('resolue', 'Résolue'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_prise_en_charge', models.DateTimeField(blank=True, null=True)),
                ('telephone_contact', models.CharField(max_length=20, verbose_name='Téléphone de contact')),
                ('personne_contact', models.CharField(blank=True, max_length=100, verbose_name='Nom de la personne à contacter')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes_medecin', models.TextField(blank=True, verbose_name='Notes du médecin')),
                ('medecin_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgences_prises_en_charge', to='sante_app.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgences', to='sante_app.patient')),
            ],
            options={
                'verbose_name': 'Urgence',
                'verbose_name_plural': 'Urgences',
                'db_table': 'Urgence',
                'ordering': ['-priorite', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NotificationUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_urgences', to='sante_app.medecin')),
                ('urgence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sante_app.urgence')),
            ],
            options={
                'verbose_name': 'Notification Urgence',
                'verbose_name_plural': 'Notifications Urgences',
                'db_table': 'NotificationUrgence',
                'ordering': ['-date_envoi'],
            },
        ),
    ]