# Generated by Django 5.2.5 on 2025-10-10 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0014_urgence_notificationurgence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sante_app.medecin'),
        ),
    ]
