# Generated by Django 5.2.5 on 2025-10-10 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0015_alter_article_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='diagnostic_chiffre',
            field=models.TextField(blank=True, verbose_name='Diagnostic chiffré'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='notes_chiffrees',
            field=models.TextField(blank=True, verbose_name='Notes chiffrées'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('read', 'Lecture'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('export', 'Export de données')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'Audit",
                'verbose_name_plural': "Logs d'Audit",
                'db_table': 'AuditLog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
