# Generated by Django 5.2.5 on 2025-10-13 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0017_medicaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='original_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='original_heure',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
