# Generated by Django 5.2.5 on 2025-10-14 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0018_rendezvous_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé'), ('RESCHEDULED', 'Reprogrammé'), ('PENDING', 'En attente'), ('TERMINE', 'Terminé')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Note (1-5)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='sante_app.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='sante_app.patient')),
                ('rendez_vous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='sante_app.rendezvous')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'db_table': 'Rating',
                'ordering': ['-date_creation'],
                'unique_together': {('patient', 'rendez_vous')},
            },
        ),
    ]
