# Generated by Django 5.2.5 on 2025-10-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0020_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Mot-clé')),
                ('response', models.TextField(verbose_name='Réponse')),
                ('category', models.CharField(choices=[('general', 'Général'), ('symptoms', 'Symptômes'), ('services', 'Services'), ('emergency', 'Urgences'), ('medication', 'Médicaments'), ('appointment', 'Rendez-vous'), ('other', 'Autre')], default='general', max_length=20, verbose_name='Catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Entrée de base de connaissances',
                'verbose_name_plural': 'Entrées de base de connaissances',
                'db_table': 'ChatbotKnowledgeBase',
                'ordering': ['keyword'],
            },
        ),
    ]
