# Generated by Django 5.2.5 on 2025-10-25 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0022_consultation_statut_consultationmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesure',
            name='consultation',
        ),
        migrations.AlterModelTable(
            name='mesure',
            table=None,
        ),
        migrations.CreateModel(
            name='Teleconsultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultation', to='sante_app.consultation')),
            ],
            options={
                'db_table': 'Teleconsultation',
            },
        ),
    ]
