# Generated by Django 5.2.5 on 2025-10-25 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0023_remove_mesure_consultation_alter_mesure_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndisponibiliteMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('raison', models.CharField(blank=True, max_length=200)),
                ('toute_la_journee', models.BooleanField(default=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='sante_app.medecin')),
            ],
            options={
                'verbose_name': 'Indisponibilité Médecin',
                'verbose_name_plural': 'Indisponibilités Médecins',
                'db_table': 'IndisponibiliteMedecin',
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree_consultation', models.IntegerField(default=30)),
                ('pause_dejeuner_debut', models.TimeField(blank=True, null=True)),
                ('pause_dejeuner_fin', models.TimeField(blank=True, null=True)),
                ('nb_max_consultations', models.IntegerField(default=10)),
                ('actif', models.BooleanField(default=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='sante_app.medecin')),
            ],
            options={
                'verbose_name': 'Disponibilité Médecin',
                'verbose_name_plural': 'Disponibilités Médecins',
                'db_table': 'DisponibiliteMedecin',
                'unique_together': {('medecin', 'jour')},
            },
        ),
    ]
