# Generated by Django 5.2.5 on 2025-10-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0024_indisponibilitemedecin_disponibilitemedecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='type_consultation',
            field=models.CharField(choices=[('cabinet', 'Consultation au cabinet'), ('teleconsultation', 'Téléconsultation en ligne')], default='cabinet', max_length=20),
        ),
    ]