# Generated by Django 5.2.5 on 2025-10-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0025_rendezvous_type_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='indisponibilitemedecin',
            name='type',
            field=models.CharField(choices=[('conges', 'Congés'), ('formation', 'Formation'), ('maladie', 'Maladie'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
