# Generated by Django 5.2.5 on 2025-10-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0026_indisponibilitemedecin_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilitemedecin',
            options={},
        ),
        migrations.RemoveField(
            model_name='disponibilitemedecin',
            name='nb_max_consultations',
        ),
        migrations.AlterField(
            model_name='disponibilitemedecin',
            name='duree_consultation',
            field=models.IntegerField(default=30, help_text='Durée en minutes'),
        ),
        migrations.AlterField(
            model_name='disponibilitemedecin',
            name='jour',
            field=models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='disponibilitemedecin',
            table=None,
        ),
    ]
