# Generated by Django 5.2.5 on 2025-10-28 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0027_alter_disponibilitemedecin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to=settings.AUTH_USER_MODEL),
        ),
    ]
