# Generated by Django 5.2.5 on 2025-10-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0028_alter_medecin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='motif_consultation',
            field=models.TextField(blank=True, help_text='Motif de la consultation', null=True),
        ),
    ]
