# Generated by Django 5.2.5 on 2025-11-01 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0029_rendezvous_motif_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('article_valide', 'Article validé'), ('article_refuse', 'Article refusé'), ('article_desactive', 'Article désactivé')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('article_titre', models.CharField(blank=True, max_length=200)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sante_app.medecin')),
            ],
            options={
                'db_table': 'Notification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
