# Generated by Django 5.2.5 on 2025-11-01 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0030_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaldocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Document médical', 'verbose_name_plural': 'Documents médicaux'},
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(max_length=100, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='file',
            field=models.FileField(upload_to='medical_documents/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='rendez_vous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sante_app.rendezvous'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload"),
        ),
    ]
