# Generated by Django 5.2.5 on 2025-11-01 22:03

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('sante_app', '0031_alter_medicaldocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]